apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: api2
  source:
    path: "HelmCharts/ApiChart"
    repoURL: "git@github.com:rhrabun/k8s-argocd-example.git"
    targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
    parameters:
      - name: "app.replicas"
        value: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
